version: '3.8'
services:
  aws:
    image: hanvitha/myapp
    ports:
      - "80:80"
    deploy:
      replicas: 3
  devops:
    image: hanvitha/mycourse
    ports:
      - "81:80"
    deploy:
      replicas: 3
  
